# Generated by Django 5.2.8 on 2025-12-28 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thoughts', models.TextField()),
                ('mood', models.CharField(max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(help_text='Score between -1 (negative) and 1 (positive)')),
                ('sentiment_label', models.CharField(help_text='e.g., Positive, Neutral, Negative', max_length=50)),
                ('analysis_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='journal.journal')),
            ],
        ),
    ]
